version: '3'
services:
  mongodb-server:
    image: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - ./data/mongo:/data/db
  ai-engine:
    build:
      context: ./ai-engine
    volumes:
      - ./ai-engine/src:/usr/myapp
      - ./data/file:/usr/mydata
  api-server:
    tty: true
    build:
      context: ./api-server
    ports:
      - '5555:5555'
    volumes:
      - ./api-server/src:/usr/myapp
      - ./data/file:/usr/mydata
    environment:
      - MONGO_URI=mongodb://mongodb-server:27017
  web-client:
    build:
      context: ./web-client
    ports:
      - '3000:3000'
    volumes:
      - ./web-client:/usr/myapp
    environment:
      - API_URL=http://api-server:5555
